version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building application..."
      - mvn clean package -DskipTests
      - echo "Moving jar to root folder..."
      - mv target/*.jar application.jar

artifacts:
  files:
    - application.jar
